theme: jekyll-theme-dinky
#jekyll-theme-architect
#jekyll-theme-cayman ... clean + modern?
#jekyll-theme-dinky
#jekyll-theme-hacker ... dark h aesthetic?
#jekyll-theme-leap-day
#jekyll-theme-merlot
#jekyll-theme-midnight
#jekyll-theme-minima
#jekyll-theme-minimal ... this looks so
#jekyll-theme-modernist
#jekyll-theme-slate ... professional + simple?
#jekyll-theme-tactile
#jekyll-theme-time-machine

title: sin's homepage
description: bookmark this to keep an eye on my updates!
